---
title: "match_boris_watlas"
author: "Niels van der Vegt"
date: "2023-10-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# SETTINGS
AGGREGATION_INTERVAL = 24  # seconds 
```

```{r message=FALSE}
library(lubridate)
library(testit)
library(stars)
library(sf)
library(ggplot2)
library(tools4watlas)
library(glue)
library(dplyr)
source('util.R')
```

```{r}
behaviour_dict <- c(
  "active"="active",
  "pecking"="active", 
  "probing"="active", 
  "hunting"="active",
  "hunting prey"="active",
  "probing prey"="active",
  "interaction"="active",
  "walking"="active",
  "foraging"="active",
  "unknown prey"="active",
  "fluttering"="active",
  "pecking prey"="active",
  "sweeping"="active",
  
  "inactive"="inactive",
  "vigilant"="inactive",
  "preening"="inactive",
  "hopping"="inactive",
  "sleeping"="inactive",
  "scratching"="inactive",
  "standing still"="inactive",
  "defacating"="inactive",
  "bathing"="inactive",
  "vomiting"="inactive",
  "stretching"="inactive",
  
  "flying"="flying",
  
  "camera malfunction"="camera malfunction"
)
```

```{r}
preprocess_observation <- function(observation_path) {
  # metadata preprocessing
  observation <- read.csv(observation_path, sep=';')
  observation_start <- observation[1,2]  # get observation date from metadata
  observation_start <- ymd_hms(observation_start, tz="Europe/Amsterdam")
  observation_lat <- as.numeric(gsub(',', '.', observation[2,2]))
  observation_long <- as.numeric(gsub(',', '.', observation[3,2]))
  observation_tag <- observation[4,2]
  colnames(observation) <- observation[6,]  # get colnames from metadata
  observation_data <- observation[-c(1:6),]  # remove metadata from df
  
  # translate the detailed behaviours into active/inactive/flying
  # change the BORIS time into a generic CEST timestamp
  observation_data$Time <- seconds(observation_data$Time) + observation_start
  observation_data <- observation_data[observation_data$Status != 'START',]
  observation_data$Behavior <- sapply(observation_data$Behavior, function(behavior) {
    return(as.character(behaviour_dict[behavior]))
  })
  
  # if the last observation was a camera malfunction, remove the last observation
  # this is often assigned after the bird flies away and is out of sight
  last_observation <- tail(observation_data, 1)
  if (last_observation$Behavior == 'camera malfunction') {
    observation_data <- head(observation_data, -1)
  }
  
  # if the last observation was flying, assume the bird flies a little longer,
  # even though this is technically not observed
  last_observation <- tail(observation_data, 1)
  if (last_observation$Behavior == 'flying') {
    # TODO we could cut the based on speed later
    observation_data[nrow(observation_data), 'Time'] <- last_observation$Time + 30
  }
  
  observation_end <- observation_data[nrow(observation_data), "Time"]
  observation_interval <- interval(observation_start, observation_end)
  
  return(
    list(
      data = observation_data,
      start = observation_start,
      end = observation_end,
      lat = observation_lat,
      long = observation_long,
      tag = observation_tag,
      interval = observation_interval
    )
  )
}
```

```{r}
get_behaviour <- function(watlas, observation) {
    watlas[,c("active", "inactive", "flying", "behaviour", "pure_behaviour")] <- t(sapply(
    1:nrow(watlas),
    FUN = function(i) {
      # TODO don't like initialising a function 1000s of times, clean up
      get_next_closest_observation <- function() {
        x <- watlas[i, "time"] - observation$data$Time
        closest <- min(abs(x[x <= 0]))
        closest_observation <- observation$data[which(x == -closest), ][1,]
        return(closest_observation)
      }
      
      # start is the the time of the previous watlas localisation
      x_start <- watlas[i, "time"] - watlas[i, "dtime"]
      # end is this localisation
      x_end <- watlas[i, "time"] 
      x_interval <- interval(x_start, x_end)
      x_next_observation <- get_next_closest_observation()
      
      # x entries should be:
      # any observations between the last localisation, and the current localisation
      # in case the current localisation is a part of an observation that stops later
      # include the next observation too
      x_entries <- rbind(
        observation$data[observation$data$Time %within% x_interval,],
        x_next_observation
      )
      
      # if one or multiple behaviours have been observed, the behaviour we assign to
      # this localisation is the behaviour that was the most common 
      # (i.e. observed the longest)
      x_behaviours <- c(
        "active" = 0, 
        "inactive" = 0, 
        "flying" = 0,
        "camera malfunction" = 0
      )
      
      # if the number of entries is one, we only have the next observation
      # and no individual observations were present in between
      if (nrow(x_entries) == 1) {
        secs <- seconds(x_end - x_start)
        x_behaviours[x_entries[1, "Behavior"]] <- x_behaviours[[x_entries[1, "Behavior"]]] + secs
      # start counting up the total amount of seconds for each behaviour
      } else {
        for (j in 1:nrow(x_entries)) {
          if (j == 1) {
            secs <- seconds(x_entries[j, "Time"] - x_start)
          } else if (j == nrow(x_entries)) {
            secs <- seconds(x_end - x_entries[j - 1, "Time"])
          } else {
            secs <- seconds(x_entries[j, "Time"] - x_entries[j - 1, "Time"])
          }
          x_behaviours[x_entries[j, "Behavior"]] <- x_behaviours[[x_entries[j, "Behavior"]]] + secs
        }
      }
      
      # if flying was observed, this observation should be flying
      # this is because the large changes in speed and location during this behavior
      if (x_behaviours[["flying"]] > 0) {
        behaviour <- "flying"
      } else {
        # else, most common behaviour
        behaviour <- names(x_behaviours[x_behaviours == max(x_behaviours)]) 
      }
      
      # pure behaviour, if only one behaviour was observed, else mixed
      pure_behaviour <- 'mixed'
      if (sum(x_behaviours) == x_behaviours[['active']]) pure_behaviour <- 'active'
      if (sum(x_behaviours) == x_behaviours[['inactive']]) pure_behaviour <- 'inactive'
      if (sum(x_behaviours) == x_behaviours[['flying']]) pure_behaviour <- 'flying'
      
      return(
        c(
          x_behaviours[["active"]],
          x_behaviours[["inactive"]],
          x_behaviours[["flying"]],
          behaviour,
          pure_behaviour
        )
      )
    }
  ))
  
  # this is why I sometimes dislike R, can't even return arguments of
  # multiple types unless you want to unpack a named list nightmare
  watlas$active <- as.numeric(watlas$active)
  watlas$inactive <- as.numeric(watlas$inactive)
  watlas$flying <- as.numeric(watlas$flying)
  return(watlas)
}


get_watlas_for_observation <- function(
    observation
  ) {
  watlas <- read.csv(glue(
    'resources/watlas/dunlin-all/dunlin-{tag}.csv',
    tag = observation$tag
  ))
  watlas$time <- ymd_hms(watlas$time, tz = "UTC")
  watlas$time <- with_tz(watlas$time, tzone = "Europe/Amsterdam") # same tz as observation
  watlas_interval <- interval(watlas[1, "time"], watlas[nrow(watlas), "time"])
  
  # create properties
  watlas <- atl_thin_data(
    watlas,
    interval=AGGREGATION_INTERVAL,
    method="aggregate"
  )
  watlas <- get_properties(watlas, x='X', y='Y')
  
  # find the overlap between the observation and the watlas data
  # then only keep the watlas localisations that were within the timeframe
  # of the observation
  overlap <- setdiff(observation$interval, watlas_interval)
  watlas <- watlas[watlas$time %within% overlap, ]
  # if there were no localisations during the observation, exit early
  if (nrow(watlas) == 0) return(NULL)
  
  # get behaviour related columns
  watlas <- get_behaviour(watlas, observation)
  
  return(watlas)
}
```

```{r}
files <- list.files('resources/observations', full.names=T)
observations <- list()
validation_data <- data.frame()

for (file in files) {
  print(file)
  observation <- preprocess_observation(file)
  watlas <- get_watlas_for_observation(observation)
  
  if (!is.null(watlas)) {
    watlas$observation_path <- file
    validation_data <- bind_rows(validation_data, watlas)
    observations[[file]] <- observation
  }
}
```

# Filtering
```{r}
# Remove very unlikely speeds
speed_max <- 120
validation_data <- validation_data[validation_data$speed_in < speed_max,]
validation_data <- validation_data[validation_data$speed_out < speed_max,]

# If camera malfunction was the most likely behavior, we don't know what happend at that WATLAS point, so we remove it
print(
  glue("Removed {n} number of localisations because of camera malfunction",
  n=nrow(validation_data[validation_data$behaviour == "camera malfunction",]))
)
validation_data <- validation_data[validation_data$behaviour != "camera malfunction",]
```

```{r}
write.table(
  validation_data, 
  glue('resources/validation_data_{AGGREGATION_INTERVAL}s.csv',
       AGGREGATION_INTERVAL=AGGREGATION_INTERVAL),
  sep=';'
)
```



